### ISSUE TITLE
At line 84 for me it works this code: <div class="tour-row">. 

### ISSUE THREAD

**Issue by tagandtag** [WebDevSimplified/Introduction-to-Web-Development#1]
https://github.com/WebDevSimplified/Introduction-to-Web-Development/blob/0ac2519b4093d23adc111cb82cf8d75b490a7c81/Introduction%20to%20CSS/Lesson%203/store.html#L84

**Comment by WebDevSimplified** [comment]
I am not 100% sure what you are trying to say with this issue, but the class of `cart-items` is needed to make the cart work with JavaScript. The `tour-row` class only adds some styling for borders and such that is not really desired for this section of the page.

**Comment by WebDevSimplified** [comment]
Inactive.
